name: Lint, Check Types, Build
on: push

jobs:
  lint-and-check-types-and-build:
    name: Lint, Check Types, Build
    runs-on: ubuntu-latest
    env:
      PGHOST: localhost
      PGDATABASE: security_vulnerability_examples
      PGUSERNAME: security_vulnerability_examples
      PGPASSWORD: security_vulnerability_examples
    steps:
      - name: Start preinstalled PostgreSQL on Ubuntu
        run: |
          sudo systemctl start postgresql.service
          pg_isready
      - name: Create database user
        run: |
          sudo -u postgres psql --command="CREATE USER security_vulnerability_examples PASSWORD 'security_vulnerability_examples'" --command="\du"
      - name: Create database and allow user
        run: |
          sudo -u postgres createdb --owner=security_vulnerability_examples security_vulnerability_examples
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1
      - run: yarn migrate up
      - run: yarn eslint . --max-warnings 0
        env:
          API_KEY: ${{ secrets.API_KEY }}
      - run: yarn tsc
      - run: yarn build
        env:
          API_KEY: ${{ secrets.API_KEY }}
          NODE_ENV: production
